### ISSUE TITLE
peer error Error: Connection failed.

### ISSUE THREAD

**Issue by masterkain** [mattermost/mattermost-plugin-calls#101]
I installed 0.6.0 today for a test drive on our mattermost 6.7.0 Team Edition instance, deployed on kubernetes via helm chart, with alb + nginx ingress.

I tested with ICE Servers `stun:stun.l.google.com:19302,stun:stun.global.calls.mattermost.com:3478`

but call drops in few seconds. anything else I can try? maybe is it about the UDP server port 8443?

<img width="768" alt="Screen Shot 2022-06-08 at 17 04 16" src="https://user-images.githubusercontent.com/12844/172650809-d1be589c-1dbd-4341-969b-be83da30a0f6.png">

**Comment by masterkain** [comment]
I see, thanks!

**Comment by masterkain** [comment]
I ended up using this:

- cluster EKS
- requires `aws-load-balancer-controller` installed on cluster
- requires [Amazon VPC CNI Amazon EKS add-on](https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html)
- this will open a NLB load balancer, so extra expenses
- assigned a CNAME to the NLB
- set it in `ICE Host Override`
- profit

hopefully this helps someone else

```
apiVersion: v1
kind: Service
metadata:
  name: mattermost-team-edition-nlb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: '8065'
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: HTTP
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /api/v4/system/ping
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-name: mattermost-team-edition-nlb
spec:
  selector:
    app.kubernetes.io/instance: mattermost
  ports:
    - port: 8443
      targetPort: 8443
      protocol: UDP
      name: talk
  type: LoadBalancer
```
